# Generated by Django 4.1.7 on 2023-05-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Login',
        ),
    ]
