# Generated by Django 4.1.7 on 2023-05-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='login',
            name='name',
        ),
    ]
